### ISSUE TITLE
Compatibility with MDX v2

### ISSUE THREAD

**Issue by hastebrot** [brillout/vite-plugin-mdx#1]
Very great work to make this vite plugin framework-independent!

I've tested this with MDX v2 (currently unreleased) by changing the dependencies in this plugin and my project. It works great and fixes some issues I have when using MDX within a react component within MDX.

```json
  "dependencies": {
    "@mdx-js/mdx": "^2.0.0-next.8",
    "@mdx-js/react": "^2.0.0-next.8",
    "@mdx-js/util": "^2.0.0-next.8",
```

- [MDX v2: ☂️ Umbrella issue · Issue #1041 · mdx-js/mdx · GitHub](https://github.com/mdx-js/mdx/issues/1041)

Example document:

```mdx
### hello page

Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum alias
vero cupiditate optio blanditiis adipisci eveniet. Error magnam
vel soluta, dolores unde laborum omnis numquam eaque itaque atque,
sunt perspiciatis.

export const Foo = ({ children, ...otherProps }) => (
  <div style={{ color: "red" }} {...otherProps}>
    {children}
  </div>
);

<Foo>
lorem **ipsum** dolor.

> foo [bar](https://example.org/)

</Foo>

```

**Comment by brillout** [comment]
Servus,

> great work to make this vite plugin framework-independent

Yep, that's the goal. Right now it only works with React but it should be easy to make it work with Vue & co. (I've an idea how to do this.)

About MDX v2; I've an idea how to allow the user to use `vite-plugin-mdx` with any MDX version. Would you be up for a PR?

**Comment by brillout** [comment]
MDX is now a peer depedency; you should now be able to use `@brillout/vite-plugin-mdx` with MDX v1 as well as MDX v2.
