### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by xiaoxiangmoe** [brillout/vite-plugin-mdx#18]
```md
# Hello

This text is written in Markdown. 1 + 1 = { (1 as number) + 1}
```

We should support ts code

**Comment by silvenon** [comment]
How would having TypeScript in MDX help you, considering that TypeScript cannot check it? 🤔

**Comment by xiaoxiangmoe** [comment]
We may use TypeScript specific syntax, such as namespaces and interfaces.

**Comment by brillout** [comment]
@xiaoxiangmoe But there wouldn't be any intellisense right?

**Comment by brillout** [comment]
Closing as this is more related to TS than vite-plugin-mdx
