### ISSUE TITLE
Usage Example?

### ISSUE THREAD

**Issue by biowaffeln** [brillout/vite-plugin-mdx#2]
Hey! I tried setting up this plugin and ran into some issues. I bootstrapped a project with `npm init @vitejs/app` and added the plugin to `vite.config.js`:

```js
import reactRefresh from "@vitejs/plugin-react-refresh";
import mdx from "@brillout/vite-plugin-mdx";

export default {
  jsx: "react",
  plugins: [reactRefresh(), mdx],
};
```
Then I created a simple `app.mdx` file that I tried to import in  `main.jsx`:
```jsx
import React from "react";
import ReactDOM from "react-dom";
import App from "./app.mdx";

ReactDOM.render(<App />, document.getElementById("root"));
```
which gives me an error in the browser window: `Uncaught SyntaxError: Invalid or unexpected token (app.mdx)`.
So... what am I missing?

**Comment by brillout** [comment]
Hi @biowaffeln 

You need to instantiate the plugin:
~~~diff
- plugins: [reactRefresh(), mdx],
+ plugins: [reactRefresh(), mdx()],
~~~

I will add proper docs later today.

**Comment by biowaffeln** [comment]
Ohhh right that worked, thanks!

**Comment by brillout** [comment]
Docs added.
