### ISSUE TITLE
Plugin usage example

### ISSUE THREAD

**Issue by krevativ** [brillout/vite-plugin-mdx#30]
Hello, I'm new to mdx, so maybe I'm doing somethign wrong, but I was trying to use this plugin with react and I wanted to enbale  syntac highlighting and line numbers. I've tryed [remark-prism](https://github.com/sergioramos/remark-prism) and [rehype-prism](https://github.com/mapbox/rehype-prism) something like follows:

```javascript
const remarkPrism = require('remark-prism');

const mdxOptions = {
  remarkPlugins: [
    remarkPrism,
  ],
  rehypePlugins: [],
}
```

But I don't see any change. Is there anything else I need to enable?

**Comment by icew4ll** [comment]
I submitted a PR to add the example but you can confirm syntax highlighting using remark-prism works on my fork now.

https://github.com/icew4ll/vite-plugin-mdx/tree/master/examples/react-remark-plugin-prism

**Comment by krevativ** [comment]
@icew4ll thanks for your help but sadly it does'n seam to work either. It's not easy to use this package just from the repository, but luckely, I'm using a workspace. So I've cloned your repository, then installed all dependencies and build it. Then I've tryed it only with remark-prism plugin, but still don't see no change. The setup is the same as in your example.

**Comment by icew4ll** [comment]
line numbers are beyond my understanding atm.  I suspect it can be done with prism plugins but haven't figured how to apply those yet or if it is possible.

**Comment by sureshjoshi** [comment]
I'm unable to get MDX plugins working with this lib. I'm using a Typescript config for Vite, with other plugins working correctly - however, as soon as I add MDX plugins, I get the following error:

```
failed to load config from /myproject/vite.config.ts
error when starting dev server:
/myproject/.yarn/cache/remark-toc-npm-8.0.0-f65d444f1e-dc272a0783.zip/node_modules/remark-toc/index.js:6
import {toc} from 'mdast-util-toc'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.external_module_.Module._load (/myproject/.pnp.cjs:23143:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/myproject/vite.config.ts:31:36)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

Note, I've tried to require("remark-toc") and import Toc from "remark-toc", both fail to work unfortunately. I'm also using Yarn 3 and PNP.

**Comment by silvenon** [comment]
You're most probably using an ESM-only version of `remark-toc-npm` in a non-ESM project. In order for you to be able to use this package you need to have `type: "module"` in your `package.json`. You have (at least) two options:

1. downgrade `remark-toc-npm` to a CommonJS version
2. add a `postinstall` script to your `package.json` which compiles `remark-toc-npm` to CommonJS, and import that in your Vite config (or wherever you're importing it)
    - ideally you should be using a `prepare` script, but Yarn 3 doesn't support it

**Comment by sureshjoshi** [comment]
Thanks @silvenon !

I tried a couple of those ideas, but I didn't try that permutation of ideas, which I guess is what crushed me in the end. Since I can pre-generate a lot of stuff (realtime MDX isn't necessary), I just wrote a python script to handle everything. 

Thanks though!

**Comment by silvenon** [comment]
Whatever works! 😉

**Comment by silvenon** [comment]
For next-level syntax highlighting I recommend the new [rehype-pretty-code](https://rehype-pretty-code.netlify.app/), it supports highlighting lines, words, and inline code!

Anyway, it seems like this issue has been resolved.
