### ISSUE TITLE
Can `resolveImport` support vite `alias` or vite `resolve` ?

### ISSUE THREAD

**Issue by Codpoe** [brillout/vite-plugin-mdx#34]
Hi, I’m currently trying to write a library that wraps `vite-plugin-mdx` and `vite-plugin-react-pages`. When I use my library by `npx`, I got the error `"react" must be installed` because **there is no `react` directory in my `node_modules`**.

So I wondered if `vite-plugin-mdx` could support `alias` of Vite so I could avoid this error in my plugin. thx 😀

**Comment by aleclarson** [comment]
Why not install `react` in your project before using `npx`?

**Comment by Codpoe** [comment]
I expect to just install a direct dependency to get the project up and running, just like vuepress

**Comment by Codpoe** [comment]
I’ve found a solution, so I’m gonna close this issue. Thx
