### ISSUE TITLE
Rendering code demo fences

### ISSUE THREAD

**Issue by jugglingcats** [brillout/vite-plugin-mdx#43]
I am trying to port a site using `gatsby-plugin-mdx-code-demo` to vite. This plugin allows you to render sample code in a normal `pre` together with the resulting generated component. See https://material-ui.com/components/buttons for an example of the type of thing.

I would like to be able to write MDX like:

~~~
// buttons.mdx

# Buttons

See below for an example of a button:

```jsx demo
    import {Button} from "@acme/controls"

    export default () => <Button>Click Me</Button>
```
~~~

I realise this is a very open question but any advice on the idiomatic way to achieve this using vite + vite-plugin-mdx would be appreciated!

**Comment by silvenon** [comment]
Yep, I would solve this with a remark plugin as well 👍 🙂 

I'm closing this as it's not related to `vite-plugin-mdx`.
