### ISSUE TITLE
MDX v2 not working

### ISSUE THREAD

**Issue by DCsunset** [brillout/vite-plugin-mdx#44]
Hello,

If I install the `@mdx-js/mdx` package and follow the instructions in README.md, everything works well.

However, if I use the `@mdx-js/mdx@next` package, an error would occur:

```
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module <project>/node_modules/@mdx-js/mdx/index.js from <project>/node_modules/vite-plugin-mdx/dist/imports.js not supported.
Instead change the require of index.js in <project>/node_modules/vite-plugin-mdx/dist/imports.js to a dynamic import() which is available in all CommonJS modules.
    at Object.requireMdx (<project>/node_modules/vite-plugin-mdx/dist/imports.js:10:12)
    at Object.createTransformer (<project>/node_modules/vite-plugin-mdx/dist/transform.js:16:27)
    at Object.configResolved (<project>/node_modules/vite-plugin-mdx/dist/index.js:46:43)
    at <project>/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:68353:127
    at Array.map (<anonymous>)
    at resolveConfig (<project>/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:68353:35)
    at async createServer (<project>/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66702:20)
    at async CAC.<anonymous> (<project>/node_modules/vite/dist/node/cli.js:687:24)
```

**Comment by silvenon** [comment]
The new MDX is published as ESM, vite-plugin-mdx is CJS, so they're not compatible yet. Not sure why the readme claims otherwise, it was probably written before MDX v2 decided for ESM. I'm interested in migrating the plugin, but I've run into some obstacles, so I'll continue later.

If you need a plugin that works with MDX v2 now, you can use `@mdx-js/rollup@next`. Make sure the `type` in your `package.json` is set to `module`, otherwise you might be able to still load it with `const mdx = await import("@mdx-js/rollup")` in an [async config](https://vitejs.dev/config/#async-config). You also need one to add this fix to your Vite config:

```js
  resolve: {
    alias: {
      "react/jsx-runtime": "react/jsx-runtime.js"
    }
  },
```

read [here](https://github.com/mdx-js/mdx/discussions/1794) for more info. I'm actually not sure if this plugin works better in any way, other than offering the special transclusion syntax.

**Comment by DCsunset** [comment]
Thank you for your detailed explanation. It works like a charm!
I can even import `@mdx-js/rollup` directly since the config file is parsed as ESM after setting `type` to `module`.

**Comment by silvenon** [comment]
Yep! I was worried Vite won't work in ESM, but it does!

**Comment by EvHaus** [comment]
Just wanted to add a bit more helpful info for others who venture here. I was successful with these steps:

- Did **not** set `type: "module"` in my `package.json`. For me this caused a ton of other issues.
- Kiaded the MDX plugin in my `vite.config.ts` like this:
```js
import { defineConfig } from 'vite';

export default defineConfig(async () => {
  const mdx = await import('@mdx-js/rollup');

  return {
    plugins: [mdx.default()]
  };
});
```
- Had to set `"target": "esnext"` in my `tsconfig.json` otherwise I was getting transpilation errors

**Comment by silvenon** [comment]
Thanks for providing the code for CJS environment! I edited my comment to link to yours for people who need CJS (which is I assume most people).

**Comment by hfabio** [comment]
> Just wanted to add a bit more helpful info for others who venture here. I was successful with these steps:
> 
> * Did **not** set `type: "module"` in my `package.json`. For me this caused a ton of other issues.
> * Added the MDX plugin in my `vite.config.ts` like this:
> 
> ```js
> import { defineConfig } from 'vite';
> 
> export default defineConfig(async () => {
>   const mdx = await import('@mdx-js/rollup');
> 
>   return {
>     plugins: [mdx.default()]
>   };
> });
> ```
> 
> * Had to set `"target": "esnext"` in my `tsconfig.json` otherwise I was getting transpilation errors

Does someone faced this kind of error?
`Uncaught SyntaxError: The requested module '/node_modules/.vite/@mdx-js_react.js?v=d545b648' does not provide an export named 'mdx'`
![image](https://user-images.githubusercontent.com/15989467/153994308-4ccd82b1-6731-47bb-8424-116956c9ffee.png)
I'm using:
- react - ^17.0.2
- vite - ^2.5.3
- @storybook/react - ^6.4.19
- storybook-builder-vite - ^0.1.15
- @mdx-js/react -^2.0.0
- @mdx-js/rollup - ^2.0.0
- vite-plugin-mdx - ^3.5.10

This is my `.storybook/main.js`:
```js
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  core: {
    builder: 'storybook-builder-vite',
  },
};
```

and this is my vite.config.ts:
```js
import { defineConfig } from 'vite';
import camelCase from 'camelcase';
import * as path from 'path';
import * as fs from 'fs';
import dts from 'vite-plugin-dts';
import eslint from 'vite-plugin-eslint';
import reactRefresh from '@vitejs/plugin-react-refresh';
import mdx from '@mdx-js/rollup';
import pkg from './package.json';

// `options` are passed to`@mdx-js/mdx`
const mdxOptions = {
  // See https://mdxjs.com/advanced/plugins
  remarkPlugins: [
    // E.g. `remark-frontmatter`
  ],
  rehypePlugins: [],
};

const getEntry = () => {
  const tsxFile = path.resolve(__dirname, 'src/index.tsx');
  if (fs.existsSync(tsxFile)) return tsxFile;
  const tsFile = path.resolve(__dirname, 'src/index.ts');
  if (fs.existsSync(tsFile)) return tsFile;
  throw new Error('Cannot find entry. (src/index.tsx or src/index.ts)');
};
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    reactRefresh(),
    eslint({ fix: true, throwOnWarning: false }),
    dts({ tsConfigFilePath: './tsconfig.build.json', insertTypesEntry: true }),
    mdx(mdxOptions),
  ],
  esbuild: {
    jsxInject: "import * as React from 'react';",
  },
  build: {
    lib: {
      entry: getEntry(),
      name: camelCase(path.basename(pkg.name)),
      fileName: (format) => `index.${format}.js`,
    },
    rollupOptions: {
      external: ['react', 'react-dom', 'styled-components'],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
          'styled-components': 'styled',
        },
      },
    },
  },
});
```

**Comment by pomber** [comment]
This is the vite config that worked for me (for React 18 + MDX v2):

```js
import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"

export default defineConfig(async () => {
  const mdx = await import("@mdx-js/rollup")
  return {
    optimizeDeps: {
      include: ["react/jsx-runtime"],
    },
    plugins: [react(), mdx.default({ remarkPlugins: [] })],
  }
})
```

From https://github.com/vitejs/vite/issues/6215#issuecomment-1106447102

**Comment by silvenon** [comment]
@pomber thanks! Added it to my summary comment earlier 👌

**Comment by csr632** [comment]
Vite hmr is not working. Neither `@mdx-js/rollup` or `@vitejs/plugin-react` does react-refresh transform to the `.mdx` files.

**Comment by imevanc** [comment]
@silvenon @EvHaus @pomber - Has anyone a workaround to consume a package that uses mdx 1.x.x in a vite-4.x.x/mdx-2.x.x project?

**Comment by silvenon** [comment]
Open a new issue if you have a question related to this plugin, providing details and preferrably a demo repository if your situation is complex.
