### ISSUE TITLE
Future of `vite-plugin-mdx`

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-mdx#5]
I'm willing to give away this Vite plugin to someone willing to maintain it.

For the npm package `vie-plugin-mdx`, see https://github.com/vitejs/vite-plugin-react-pages/issues/6

CC @csr632 (the author of https://github.com/vitejs/vite-plugin-react-pages/tree/master/packages/vite-plugin-mdx)

**Comment by brillout** [comment]
Note that I will maintain this in the meantime.

**Comment by brillout** [comment]
@ajstrand In case you're interested. We could co-maitain then I'll eventually leave it all to you.

**Comment by ajstrand** [comment]
I'd be happy to co-maintain. I dont know a ton about the internals of MDX, but it seems like the intregration with frameworks would be fairly small. Only React/Preact/Vue most likely? The svelte ecosystem seems to have their own MDX-like package https://github.com/pngwn/MDsveX.

**Comment by ajstrand** [comment]
As far as maintaining the plugin by myself, I dont think that would be terribly hard, as long as the plugins scope doesn't get too big.

**Comment by brillout** [comment]
👍 Added you as maintainer of `@brillout/vite-plugin-mdx`. Let's co-maintain for a while and then we can move it to https://github.com/ajstrand/vite-plugin-mdx.

> Only React/Preact/Vue most likely

Looking at https://github.com/mdx-js/mdx/tree/main/packages it seems like there are only integrations for React, Preact, and Vue. So we're only missing Vue and then we are feature complete I guess?

> plugins scope doesn't get too big.

Feature-wise, it seems like only Vue support is missing (but I don't know much about MDX either). I don't see how scope would grow much.

**Comment by ajstrand** [comment]
From the conversation you were having inn the other MDX repo for vite, it appears that the general consensus is that folks are wanting to move towards thee other vite plugin mdx and have this plugin be deprecated.
 I see no issue with that as long as the two projects have the same goals and one isnt a duplicate of the other.

**Comment by brillout** [comment]
I see the confusion, let me clarify.

Current state:
 - https://github.com/brillout/vite-plugin-mdx is published as https://www.npmjs.com/package/@brillout/vite-plugin-mdx
 - https://github.com/vitejs/vite-plugin-react-pages/tree/master/packages/vite-plugin-mdx is published as https://www.npmjs.com/package/vite-plugin-mdx

Proposed state:
 - https://github.com/brillout/vite-plugin-mdx is published as https://www.npmjs.com/package/vite-plugin-mdx
 - https://www.npmjs.com/package/@brillout/vite-plugin-mdx is deprecated
 - https://github.com/vitejs/vite-plugin-react-pages/tree/master/packages/vite-plugin-mdx is deprecated

**Comment by ajstrand** [comment]
Ok, thanks for clarifying, your explanation makes more sense. I'm onboard with the proposed plan.

**Comment by brillout** [comment]
https://github.com/brillout/vite-plugin-mdx is now live as https://www.npmjs.com/package/vite-plugin-mdx

I invited @silvenon as collaborator.

I guess we can close this ticket for now.

If anyone wants to join in maintaining vite-plugin-mdx, let us know in this ticket.

**Comment by felixakiragreen** [comment]
🙏 @brillout just wanted to thank you for your continued maintenance of this package. I just switched to using Vite, and it thrills me that there is support for MDX. I just got it set up and working within 5 minutes because of your excellent documentation. Thanks again!

**Comment by brillout** [comment]
:-)
